[package]
authors.workspace = true
description = "Core business logic for the Template-Teleporter"
edition = "2021"
license-file.workspace = true
name = "template_teleporter_core"
repository.workspace = true
version.workspace = true

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
sha2 = "0.10"
hex = "0.4"
serde_yaml = "0.9"

[dev-dependencies]
tempfile = "3.6"
